defaults:
  - class_transfer_method:
      - linear_interp_custom_guidance_inverted_start
      - classifier_free_guidance_forward_start
      - ddib
  - dataset: BBBC021_comp_conc_nice_phen_high_conc_balanced_no_aug
  - pipeline:
      - DDIM
      - SD
  - _self_
  - batch_sizes: a100-80gb

exp_parent_folder: ${oc.env:SCRATCH}/comparison-experiments/experiments

project: class_transfer
run_name: REMOVEME_test_run

hydra:
  run:
    dir: ${exp_parent_folder}/${project}/${run_name} # will replace/append to files if relaunched!

output_folder: ${hydra:run.dir}

debug: false
monitor: false
slurm: true

mixed_precision: fp16
num_GPUs: 1

compute_fid: true
compute_isc: true
compute_kid: true
kid_subset_size: 1000 # 1000 is the default
