SD:
  # instantiation args
  _target_: src.custom_pipeline_stable_diffusion_img2img.CustomStableDiffusionImg2ImgPipeline.from_pretrained
  pretrained_model_name_or_path: experiments/SD_100_perc/full_pipeline_save
  # torch_dtype: fp16

  # other args; these "are not expected [...] and will be ignored" at instantiation
  num_inference_steps: 100
  eval_batch_size: 512
